### PR TITLE
fix: prevent undefined error when no options are given

### LINKED ISSUE #84: Undefined error when running without options
I'm using a simple `await backstop(assert);` to test, and since one of the last version it's throwing an error 

```
Source: 	
TypeError: Cannot read properties of undefined (reading 'testId')
    at createNameHash (http://localhost:4200/assets/test-support.js:7321:33)
    at _default (http://localhost:4200/assets/test-support.js:7362:18)
    at Object.<anonymous> (http://localhost:4200/assets/tests.js:27:37)
```

I think it stems from this PR: https://github.com/garris/ember-backstop/pull/83

Because in my case I didn't pass anything `options` is undefined in the new line `testHash.testId = options.testId ?? window._testRunTime;`

Passing an empty object as option fixes the error but I'll prepare a PR to prevent this in future.

### PR DESCRIPTION
**Pull request by gvdp**
Fixes #84

### CODE REVIEW

**Review by garris — APPROVED** [review]
Thank you!

**Comment by villander** [comment]
@garris could you please release this change? I'd love to get it into my project. 😄

**Comment by derrabauke** [comment]
:up: me2

**Comment by garris** [comment]
oh jeez. Sorry for the delay.  Pushed to NPM.

**Comment by derrabauke** [comment]
Awesome! Thank you so much for the release @garris ! :pray:

**Pull request merged**
