### PR TITLE
Support usage of testId option when creating the testHash

### PR DESCRIPTION
**Pull request by dannycalleri**
This Pull Request does the following:

- solves problem identified in the following issue: https://github.com/garris/ember-backstop/issues/82
- adds regression tests for old behavior
- adds new test for the new behavior

### CODE REVIEW

**Comment by garris** [comment]
Wow.  The quality of this commit is really high.  Nicely done.

**Comment by dannycalleri** [comment]
> Wow. The quality of this commit is really high. Nicely done.

Thanks for your feedback 🙏 
Are you planning the release anytime soon?

**Comment by garris** [comment]
Will try to get this out today.---------------------------Sent from my 📱.On May 22, 2023, at 7:29 AM, Danny Calleri ***@***.***> wrote:﻿

Wow. The quality of this commit is really high. Nicely done.

Thanks for your feedback 🙏
Are you planning the release anytime soon?

**Comment by garris** [comment]
@dannycalleri  This is published.  Thanks for the PR.

```
A new version of the package ember-backstop (1.5.2) was published at 2023-05-25T19:09:11.998Z from
23.93.181.80. The shasum of this package was 37c67756d4edacb62c4d1fa995094fb6162f1152.
```

**Pull request merged**
